// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnsweringNode: typeof import('./src/components/answer/AnsweringNode.vue')['default']
    App: typeof import('./src/components/App.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FillAnswerNode: typeof import('./src/components/editor/FillAnswerNode.vue')['default']
    FreeAnswerNode: typeof import('./src/components/editor/FreeAnswerNode.vue')['default']
    InterfaceBase: typeof import('./src/components/InterfaceBase.vue')['default']
    MultiAnswerNode: typeof import('./src/components/editor/MultiAnswerNode.vue')['default']
    VueEditor: typeof import('./src/components/editor/VueEditor.vue')['default']
  }
}
